name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests
      - name: Start server
        run: |
          nohup uvicorn app.server:app --host 0.0.0.0 --port 8000 &
          sleep 2
      - name: Smoke test /health
        run: |
          python -c "import requests; r = requests.get('http://127.0.0.1:8000/health'); print('health', r.status_code, r.text); assert r.status_code == 200"
      - name: Smoke test /recommend
        run: |
          python -c "import requests; r = requests.post('http://127.0.0.1:8000/recommend', json={'query':'sci-fi','top_k':3}); print('recommend', r.status_code, r.text); assert r.status_code == 200"
